/* eslint-disable import/prefer-default-export */
/* Populated by react-webpack-redux:action */
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const GET_BITCOIN_STATS = 'GET_BITCOIN_STATS';
export const GET_BITCOIN_STATS_SUCCESS = 'GET_BITCOIN_STATS_SUCCESS';
export const GET_BITCOIN_STATS_ERROR = 'GET_BITCOIN_STATS_ERROR';
export const GET_EXCHANGE_RATES = 'GET_EXCHANGE_RATES';
export const GET_EXCHANGE_RATES_SUCCESS = 'GET_EXCHANGE_RATES_SUCCESS';
export const GET_EXCHANGE_RATES_ERROR = 'GET_EXCHANGE_RATES_ERROR';
export const GET_BITCOIN_ADDRESSES = 'GET_BITCOIN_ADDRESSES';
export const GET_BITCOIN_ADDRESSES_SUCCESS = 'GET_BITCOIN_ADDRESSES_SUCCESS';
export const GET_BITCOIN_ADDRESSES_ERROR = 'GET_BITCOIN_ADDRESSES_ERROR';
export const ADD_BITCOIN_ADDRESS = 'ADD_BITCOIN_ADDRESS';
